services:
  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - pg-data:/var/lib/postgresql
    networks:
      - shared

  be: 
    build:
      context: backend
      target: development
      ports: 8080
      environment: 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:?Db password missing}
      - DB_NAME=${DB_NAME:-todo}

    networks:
      - shared
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore: 
            - 

  fe:
    build: 
      context: frontend
      target: development
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore: 
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

volumes:
  pg-data:
networks:
  shared:
    name: tms-nw
    external: true
