services:
  fe:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    environment:
      - VITE_REACT_API_URL=${VITE_REACT_API_URL:-http://localhost:8080}
    develop:
      watch:
        - action: sync
          path: frontend
          target: /app
          ignore: 
            - node_modules/
        - action: rebuild
          path: frontend/package.json
  be:
    build: 
      context: backend # required for dockerfile
      target: development
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/go.mod
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-tms-db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:?Db password missing}
  db:
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:?Db password required}
      - POSTGRES_DB=${DB_NAME:-tms-db}
    volumes: 
      - pg_data:/var/lib/postgresql
  
volumes:
  pg_data:
