services:
  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - pg-data:/var/lib/postgresql

  fe:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          initial_sync: true
          ignore: 
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

volumes:
  pg-data:
