const data = [
  {
    id: 1,
    title: "Fix login issue",
    description: "Users are unable to log in with Google authentication.",
    status: "In Progress",
    createdAt: 1708590600,
    updatedAt: 1708596000,
  },
  {
    id: 2,
    title: "Add dark mode",
    description: "Implement a toggle switch to enable dark mode.",
    status: "Pending",
    createdAt: 1708505700,
    updatedAt: 1708505700,
  },
  {
    id: 3,
    title: "Optimize database queries",
    description: "Improve query performance for fetching large datasets.",
    status: "Completed",
    createdAt: 1708428300,
    updatedAt: 1708492200,
  },
  {
    id: 4,
    title: "Refactor frontend components",
    description: "Break down large components into reusable smaller ones.",
    status: "In Review",
    createdAt: 1708402800,
    updatedAt: 1708582200,
  },
  {
    id: 5,
    title: "Improve accessibility",
    description: "Ensure the app is fully accessible for screen readers.",
    status: "Pending",
    createdAt: 1708320600,
    updatedAt: 1708320600,
  },
  {
    id: 6,
    title: "Write unit tests",
    description: "Increase test coverage for critical components.",
    status: "In Progress",
    createdAt: 1708294800,
    updatedAt: 1708572000,
  },
  {
    id: 7,
    title: "Fix mobile responsiveness",
    description: "Ensure the app layout adapts well to all screen sizes.",
    status: "Completed",
    createdAt: 1708208400,
    updatedAt: 1708471200,
  },
  {
    id: 8,
    title: "Migrate to TypeScript",
    description: "Refactor existing JavaScript codebase to TypeScript.",
    status: "In Progress",
    createdAt: 1708122000,
    updatedAt: 1708550400,
  },
  {
    id: 9,
    title: "Update dependencies",
    description: "Upgrade outdated npm packages to their latest versions.",
    status: "Pending",
    createdAt: 1708035600,
    updatedAt: 1708035600,
  },
  {
    id: 10,
    title: "Implement CI/CD pipeline",
    description: "Automate deployment using GitHub Actions and Docker.",
    status: "In Review",
    createdAt: 1707949200,
    updatedAt: 1708543200,
  },
];

export default data;
